name: voiceappEnv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1.1
  - matplotlib=3.4.2
  - numpy=1.20.3
  - pandas=1.3.2
  - pillow=8.3.1
  - python=3.8.11
  - pytorch=1.9.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tqdm=4.62.1=pyhd3eb1b0_1
